AWSTemplateFormatVersion: 2010-09-09
Description: |
  The Milliseconds Converter Application aims to convert the given time in milliseconds into hours, minutes, and seconds. The application is to be coded in Python and deployed as a web application with Flask on AWS Application Load Balancer with Auto Scaling Group of Elastic Compute Cloud (EC2) Instances using AWS Cloudformation Service.
Parameters:
  
Mappings:
  
Conditions:
  
Resources:
  
  MiliTargetGrp:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckEnabled: Boolean
      HealthCheckIntervalSeconds: Integer
      HealthCheckPath: String
      HealthCheckPort: String
      HealthCheckProtocol: String
      HealthCheckTimeoutSeconds: Integer
      HealthyThresholdCount: Integer
      Matcher:
        Matcher
      Name: String
      Port: Integer
      Protocol: String
      Tags:
        - Tag
      TargetGroupAttributes:
        - TargetGroupAttribute
      TargetType: String
      Targets:
        - TargetDescription
      UnhealthyThresholdCount: Integer
      VpcId: String
  
  
  MiliSecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: enables SSH and HTTP #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0


      Tags:
        - Tag
        
Outputs: