apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql
    app: mysql-service
spec:
  selector:
    name: mysql-pod
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
