apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql
    app: mysql-app
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
