apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-pod
    spec:
      containers:
      - image: mysql:5.7
      imagePullPolicy: Always
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: P123456p 
        - name: "MYSQL_DATABASE_HOST"
          value: "mysql-service"
        - name: "MYSQL_DATABASE_PASSWORD"
          value: "Clarusway_1"
        - name: "MYSQL_DATABASE_DB"
          value: "mysql"
        - name: "MYSQL_USER"
          value: "admin"
      ports:
      - containerPort: 3306
        volumeMounts:
        - name: mysql-pv-storage
        mountPath: /var/lib/mysql
    volumes:
    - name: mysql-pv-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim
                      
