apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web-server
    app: web-server-app
spec:
  selector:
    name: web-server 
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
     nodePort: 30001
